name: Deploy README Styles

on:
  push:
    branches: [ main ]
    paths:
      - 'README.md'
      - '.github/styles.css'
  pull_request:
    branches: [ main ]
    paths:
      - 'README.md'
      - '.github/styles.css'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Deploy Styles
        run: |
          # 创建 gh-pages 分支
          git checkout --orphan gh-pages
          git rm -rf .
          
          # 复制样式文件
          mkdir -p .github
          cp ../.github/styles.css .github/
          
          # 提交更改
          git add .
          git commit -m "Deploy README styles"
          git push origin gh-pages --force
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 